# Use an official Go runtime as the base image
FROM golang:1.17-alpine

# Set the working directory inside the container
WORKDIR /app

COPY ../ .

# Set the entry point for the container
CMD ["sleep", "infinity"]
